name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov fastapi httpx sqlalchemy

    - name: Print Python version and installed packages
      run: |
        python --version
        pip list

    - name: Print app directory contents
      run: |
        ls -la app

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=term-missing -v
