name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov fastapi httpx

    - name: Print Python version and installed packages
      run: |
        python --version
        pip list

    - name: Print app directory contents
      run: |
        ls -la app

    - name: Run tests with coverage
      run: |
        pytest --cov=app --cov-report=term-missing -v

    - name: Commit coverage report
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add coverage report"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
